const INCREMENT = "INCREMENT"
const DECREMENT = "DECREMENT"
const FACEIDTOEKNREQUEST = "FACEIDTOEKNREQUEST"

const FETCH_BEGIN = "FETCH_BEGIN"
const FETCH_ERROR = "FETCH_ERROR"
const FETCH_SUCCESS = "FETCH_SUCCESS"


export {
    INCREMENT,
    DECREMENT,
    FETCH_BEGIN,
    FETCH_ERROR,
    FETCH_SUCCESS,
    FACEIDTOEKNREQUEST
}